spring.datasource.url=jdbc:postgresql://localhost:5432/medify
spring.datasource.username=medify_user
spring.datasource.password=medify_pass
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration